disabled_rules:
  - trailing_whitespace
  - force_cast
  - cyclomatic_complexity
  - function_body_length
  - nesting
  - statement_position
  - identifier_name
  - opening_brace
  - comma
  - unused_optional_binding
  - closure_parameter_position
  - trailing_comma
  - duplicate_enum_cases
  - todo

opt_in_rules:
  - force_unwrapping

line_length: 150

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 600
  error: 800

excluded:
  - Carthage
  - Pods
  - Vendors
  - Frameworks
  - Fastlane
  - 'SayTheirNamesTests'
  - 'SayTheirNamesUITests'
  - 'Pods'
